### ISSUE TITLE
internal 500 error

### ISSUE THREAD

**Issue by buzucan** [fedeandri/auto-approve-comments#4]
i'm using php7 and nginx+letencrypt.
When i post(comment) something as a list user all is fine, but when i m not in list it gives me internal 500 error.

Do you know what is the problem?

**Comment by fedeandri** [comment]
I'll try to see if I can replicate the problem using your same configuration then I'll get back to you

**Comment by buzucan** [comment]
i found the issue. Is having problems with tako plugin https://wordpress.org/plugins-wp/tako-movable-comments/
After deactivated it is ok...

**Comment by fedeandri** [comment]
Ok, I'll try to install it and see what's going on, thanks for pointing that out

**Comment by buzucan** [comment]
and a sugestion, i think there is a feature. :)

I have and Simple Comment Editing https://ro.wordpress.org/plugins/simple-comment-editing/ for people who wants to edit their posts. When an auto approved comment is edited the comment goes in moderation.

There is something to do?! :)

**Comment by fedeandri** [comment]
No worries, will look into that too :)
By the way if you have new features suggestions feel free to get in touch again (maybe open a new issue here or in the WordPress support forum)

**Comment by buzucan** [comment]
sure :)
